version: "3.8"

services:
  frontend:
    build: nginx-front
    restart: always
    volumes:
      - ./nginx-front/vhost.d:/etc/nginx/conf.d
      - ./build:/usr/share/nginx/html
    ports:
      - 8001:8001
    env_file:
      - ./.env_web_app

networks:
  default:
    name: shared-web
    external: true
